import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { store } from '../app/store/store';
import { Provider } from 'react-redux'

const popins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     {/* <Provider store={store}> */}
      <body className={popins.className}>{children}</body>
    {/* </Provider> */}
    </html>
  )
}
